<?php /* @see NoName_P24Acquire_Block_PaymentInformation */ ?>
<?php /* @var $this NoName_P24Acquire_Block_PaymentInformation */ ?>

<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li><?php echo $this->__("Visa / MasterCard credit cards payment effected through the Privat24 payment system.") ?></li>
    <li><?php echo $this->__("Credit card's data input is making on the site's purchasing system. You will be redirected on the payment's page after confirmation of your order on the next step.") ?></li>
</ul>